-- Create notifications table
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow public read access to notifications" ON notifications FOR SELECT USING (true);
CREATE POLICY "Allow public insert to notifications" ON notifications FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to notifications" ON notifications FOR UPDATE USING (true); -- For marking as read

-- Seed some initial data if empty
INSERT INTO notifications (title, description, created_at)
SELECT 'New Order Received — #ORD-24095', 'A new order worth £250 has been placed by Abiola Ogunseye.', NOW() - INTERVAL '3 hours'
WHERE NOT EXISTS (SELECT 1 FROM notifications);

INSERT INTO notifications (title, description, created_at)
SELECT 'Low Stock Warning — Okada Rice (5kg)', 'Only 3 units remaining. Consider restocking soon.', NOW() - INTERVAL '12 minutes'
WHERE NOT EXISTS (SELECT 1 FROM notifications WHERE title = 'Low Stock Warning — Okada Rice (5kg)');
